### ISSUE TITLE
HG6143D1_KEY

### ISSUE THREAD

**Issue by catbei2020** [PTCRY233/HG6143D1_KEY#1]
上海电信亲测无效，新版的HG6143D1貌似修复了这个bug，超管界面无法访问

**Comment by PTCRY233** [comment]
能提供点截图吗？我看看

**Comment by ARCHERXTY** [comment]
![网页](https://github.com/PTCRY233/HG6143D1_KEY/assets/59302439/419a64ea-77dd-484e-98f4-8b5bf48a37c8)
![telnet](https://github.com/PTCRY233/HG6143D1_KEY/assets/59302439/4066ccd7-cf74-4c34-9906-2d3bdcb0feb3)

**Comment by PTCRY233** [comment]
如果192.168.1.1都进不去的话就算了吧，可以进去的话就登陆一下普通账户，再试试脚本提供的链接。再不然可以试试长按光猫的复位孔恢复出厂设置
